name: knc_web
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.9.1 <3.0.0'

dependencies:
  mdc_web: ^0.4.0
#  path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  sass_builder: ^2.1.2
  pedantic: ^1.9.0
