name: knc.angular.dart
description: Angular FrontEnd for KNC Project
version: 0.0.1

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_forms: ^2.1.2
  # update to the latest version
  bootstrap_sass: any

dev_dependencies:
  build_runner: ^1.7.0
  build_test: ^0.10.2
  build_web_compilers: ^2.6.1
  sass_builder: ^2.1.2

  angular_test: ^2.3.0
  pageloader: ^3.2.0
  test: ^1.6.0
